//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use async_trait::async_trait;
use infra::uuid::Uuid;
use sea_orm::{
  entity::prelude::*, ActiveModelBehavior, ActiveModelTrait, DerivePartialModel, FromQueryResult,
  Set,
};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "attribute_option")]
#[serde(rename_all(serialize = "camelCase", deserialize = "snake_case"))]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  #[sea_orm(column_type = "Text")]
  pub value: String,
  #[sea_orm(column_type = "Uuid")]
  pub attribute_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::attribute::Entity",
    from = "Column::AttributeId",
    to = "super::attribute::Column::Id"
  )]
  Attribute,
}

impl Related<super::attribute::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Attribute.def()
  }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
  fn new() -> Self {
    Self {
      id: Set(Uuid::new()),
      ..ActiveModelTrait::default()
    }
  }
}

#[derive(Debug, DerivePartialModel, Serialize, FromQueryResult)]
#[sea_orm(entity = "Entity")]
#[serde(rename_all = "camelCase")]
pub struct PartialModel {
  pub id: Uuid,
  pub value: String,
}
